version: "3.8"
services:
  react-app:
    container_name: react-app
    build: ./docker/react
    volumes:
      - ./react-app:/react-app
    working_dir: /react-app
    command: sh -c "yarn start"
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./api:/var/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  api:
    container_name: rest-api
    build: ./docker/php-fpm
    volumes:
      - ./api:/var/www/api
  db:
    container_name: db
    image: mysql:5.7
    platform: linux/amd64
    environment:
        MYSQL_DATABASE: pj_management
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
        TZ: "Asia/Tokyo"
    ports:
        - "3306:3306"
    command: mysqld --innodb_use_native_aio=0
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
