version: "3.8"
services:
  frontend:
    build: ./dockerfiles/frontend
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    command: sh -c "yarn start"
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true